CREATE DATABASE MUSIC_DATA
USE MUSIC_DATA
CREATE TABLE INFO_SONG(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
NAME_SONG NVARCHAR(255) NOT NULL,
PATH_SONG VARCHAR(255) NOT NULL,
ARTIST NVARCHAR(255) NOT NULL,
TIME_SONG VARCHAR(255) NOT NULL,
ALBUM NVARCHAR(255) NOT NULL,
TOPIC NVARCHAR(255) NOT NULL,
LIKED INT NOT NULL
);
CREATE TABLE DS_LIST(
ID INT NOT NULL IDENTITY(1,1),
NAME_LIST NVARCHAR(255) NOT NULL,
PRIMARY KEY (ID)
);
CREATE TABLE LIST_LIKED(
ID INT NOT NULL IDENTITY(1,1),
NAME_SONG NVARCHAR(255) NOT NULL,
PRIMARY KEY (ID)
);
DROP TABLE INFO_SONG
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES ( '2004', '2004', N'Cá hồi hoang', '04:15', 'vita-mood','ballad',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES ( N'Ánh đèn phố', 'AnhDenPho', 'The Cassette', '04:42', N'Rừng đom đóm', 'indie',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Ánh sáng','AnhSang', N'Cá hồi hoang','03:20',N'Ngày ấy và sau này', 'ballad',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES('BandaMusical','BandaMusical',N'Cá hồi hoang', '08:40', N'Gấp', 'indie',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Bước qua mùa cô đơn', 'BuocQuaMuaCoDon', 'Vũ.','05:42',N'Một vạn năm','top-hit',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Cá rô','CaRo', 'The Cassette', '02:58',N'Rừng đom đóm', 'indie',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Có một người luôn chờ khi anh đến', 'CoMotNguoiLuonCuoiKhiAnhDen', 'Tây Nguyên Sound', '04:34', 'Single', 'rap',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Có thể', 'CoThe', N'Cá hồi hoang','03:35', N'Gấp','ballad',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Cuộc đời có bao điều mình sẽ mãi chưa làm', 'CuocDoiConBaoNhieuDieuMinhSeMaiChuaLam', N'Cá hồi hoang', '03:53',N'Ngày ấy và sau này', 'top-hit',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Đã lỡ yêu em nhiều','DaLoYeuEmNhieu', 'Justatee','04:26','Single', 'top-hit',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Đợi','Doi',N'Cá hồi hoang', '05:30', N'Gấp', 'ballad',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Đông kiếm em','DongKiemEm','Vũ.', '04:06', 'Single', 'top-hit',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Ghé quá', 'GheQua', 'Tây Nguyên Sound', '04:28', 'Single', 'rap',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Già cùng nhau là được', 'GiaCungNhauLaDuoc', 'Tây Nguyên Sound', '03:54', 'Single', 'rap',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES('July', 'July', 'The Cassette', '03:54','Single', 'top-hit',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Khảng cách', 'KhoangCach', 'The Cassette', '05:31',N'Rừng đom đóm','indie',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Lạ lung', 'LaLung', 'Vũ.', '04:21','Single','top-hit',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Lời yêu em', 'LoiYeuEm', 'The Cassette', '04:45','Singl','indie',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Mắt biếc', 'MatBiec', 'Tây Nguyên Sound', '04:45', 'Single', 'rap',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Mây lang thang', 'MayLangThang', 'Tây Nguyên Sound', '03:19', 'Single', 'rap',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Một màu', 'MotMau', N'Cá hồi hoang', '04:04',N'Ngày ấy và sau này','ballad',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Một thuở thanh bình', 'MotThuoThanhBinh', 'Tây Nguyên Sound', '04:12', 'Single', 'rap',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Mùa hè của em', 'MuaHeCuaEm', 'Vũ.', '04:17', 'Single', 'indie',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Mưa ngâu nằm cạnh', 'MuaNgauNamCanh', 'Vũ.', '04:32', 'Single', 'top-hit',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Nắng', 'Nang', 'The Cassette', '04:29', 'Single', 'indie',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Ngày ấy và sau này', 'NgayAyVaSauNay', N'Cá hồi hoang', '03:39',N'Ngày ấy và sau này', 'ballad',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Ngày xa lắm', 'NgayXaLam', N'Cá hồi hoang', '05:11','Giấc mơ giấy','indie',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES('No internet', 'NoInternet', '7Uppercuts', '03:12','Single','indie',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Phòng trống', 'PhongTrong', N'Cá hồi hoang', '04:47',N'Ngày ấy và sau này','ballad',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Phút ban đầu', 'PhutBanDau', 'Vũ.', '04:00', 'Single','top-hit',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Tầng thượng 102', 'TangThuong102', N'Cá hồi hoang', '03:57', N'Gấp','indie',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Tháng 10 cho em', 'Thang10ChoEm', 'Tây Nguyên Sound', '03:36', 'Single','rap',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Thằng điên', 'ThangDien', 'Justatee', '04:46', 'Single','top-hit',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Thôi Trễ Rồi, Chắc Anh Phải Về Đây', 'ThoiTreRoiChacAnhPhaiVeDay', 'Tây Nguyên Sound', '03:30', 'Single','rap',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Trốn tìm', 'TronTim', '7Uppercuts', '03:30','Single','indie',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Tựa đêm nay', 'TuaDemNay', 'The Cassette', '04:55',N'Rừng đom đóm','indie',0)
INSERT INTO INFO_SONG(NAME_SONG, PATH_SONG, ARTIST, TIME_SONG, ALBUM, TOPIC, LIKED)
VALUES(N'Yêu', 'Yeu', '7Uppercuts', '03:06','Single','indie',0)
SELECT * FROM dbo.LIST_LIKED
SELECT * FROM dbo.DS_LIST
SELECT * FROM dbo.DS_LIST
DELETE FROM DS_LIST WHERE NAME_LIST ='tmp'
-----------------------------------------
INSERT INTO LIST_LIKED(NAME_LIST) VALUES('LIST_LIKED')
SELECT * FROM dbo.INFO_SONG, dbo.LIST_LIKED as liked WHERE  PATH_SONG = liked.NAME_SONG and liked.ID = 5
SELECT * FROM dbo.INFO_SONG WHERE ID = 7
CREATE TABLE [N"Nhạc là"] (
ID INT NOT NULL IDENTITY(1,1),
NAME_SONG NVARCHAR(255) NOT NULL,
PRIMARY KEY (ID)
);
SELECT * FROM DS_LIST
SELECT * FROM [Nhạc là để chill]

DELETE FROM [DS_LIST] WHERE NAME_SONG ='LIST_LIKED'